// Client/ResSystem/UIResourceTables.cpp
#include "UIResourceTables.h"
#include <map>
namespace fiesta {

#define _NC_ENTRY(name) { name, #name }
struct NCNameEntry { NCOpcode nc; const char* sz; };
static const NCNameEntry s_aTable[] = {
    _NC_ENTRY(NC_USER_LOGINFAIL_ACK), _NC_ENTRY(NC_USER_CLIENT_VERSION_CHECK_REQ),
    _NC_ENTRY(NC_USER_LOGIN_REQ), _NC_ENTRY(NC_USER_LOGIN_ACK),
    _NC_ENTRY(NC_USER_WORLD_STATUS_REQ), _NC_ENTRY(NC_USER_WORLD_STATUS_ACK),
    _NC_ENTRY(NC_USER_WORLD_SELECT_REQ), _NC_ENTRY(NC_USER_WORLD_SELECT_ACK),
    _NC_ENTRY(NC_USER_LOGOUT_REQ), _NC_ENTRY(NC_USER_LOGOUT_ACK),
    _NC_ENTRY(NC_CHAR_LOGIN_REQ), _NC_ENTRY(NC_CHAR_LOGIN_ACK),
    _NC_ENTRY(NC_CHAR_LOGOUT_CMD),
    _NC_ENTRY(NC_MAP_LOGIN_REQ), _NC_ENTRY(NC_MAP_LOGIN_ACK),
    _NC_ENTRY(NC_ACT_MOVERUN_CMD), _NC_ENTRY(NC_ACT_MOVEWALK_CMD),
    _NC_ENTRY(NC_ACT_STOP_CMD), _NC_ENTRY(NC_ACT_CHAT_REQ), _NC_ENTRY(NC_ACT_CHAT_CMD),
    _NC_ENTRY(NC_BAT_NORMALATTACK_CMD), _NC_ENTRY(NC_BAT_DAMAGE_CMD),
    _NC_ENTRY(NC_BAT_DEAD_CMD), _NC_ENTRY(NC_BAT_LEVELUP_CMD),
    _NC_ENTRY(NC_BAT_SKILL_USE_REQ), _NC_ENTRY(NC_BAT_SKILL_USE_ACK),
    _NC_ENTRY(NC_BAT_ABSTATESET_CMD), _NC_ENTRY(NC_BAT_ABSTATERESET_CMD),
    _NC_ENTRY(NC_ITEM_USE_REQ), _NC_ENTRY(NC_ITEM_EQUIP_REQ),
    _NC_ENTRY(NC_NPC_MENU_OPEN_CMD), _NC_ENTRY(NC_NPC_SHOP_BUY_REQ),
    _NC_ENTRY(NC_QUEST_BEGIN_REQ), _NC_ENTRY(NC_QUEST_END_REQ),
    _NC_ENTRY(NC_PARTY_REQ), _NC_ENTRY(NC_GUILD_CREATE_REQ),
    _NC_ENTRY(NC_TRADE_REQ), _NC_ENTRY(NC_BOOTH_OPEN_REQ),
    _NC_ENTRY(NC_AUCTION_LIST_REQ), _NC_ENTRY(NC_KQ_QUEUE_REQ),
    _NC_ENTRY(NC_MID_QUEUE_REQ), _NC_ENTRY(NC_PET_SUMMON_REQ),
    _NC_ENTRY(NC_GAMBLE_DICE_REQ), _NC_ENTRY(NC_ATTEND_GET_CMD),
    _NC_ENTRY(NC_TITLE_GAIN_CMD), _NC_ENTRY(NC_PROD_BEGIN_REQ),
    _NC_ENTRY(NC_CHAT_NORMAL_CMD), _NC_ENTRY(NC_CHAT_PARTY_CMD),
    _NC_ENTRY(NC_FRIEND_ADD_REQ), _NC_ENTRY(NC_HOLY_PROPOSE_REQ),
    _NC_ENTRY(NC_PRISON_ENTER_CMD), _NC_ENTRY(NC_OPTOOL_AUTH_REQ),
    _NC_ENTRY(NC_INTER_HELLO_REQ), _NC_ENTRY(NC_INTER_AUTH_TOKEN_PUSH)
};
#undef _NC_ENTRY
static const size_t kCount = sizeof(s_aTable) / sizeof(s_aTable[0]);

const char* NCName(NCOpcode nc) {
    for (size_t i = 0; i < kCount; ++i) if (s_aTable[i].nc == nc) return s_aTable[i].sz;
    return "NC_UNKNOWN";
}

NCOpcode ParseNCName(const std::string& rName) {
    for (size_t i = 0; i < kCount; ++i) if (rName == s_aTable[i].sz) return s_aTable[i].nc;
    return (NCOpcode)0;
}

} // namespace fiesta
