// Server/Zone/CardCollection/CardCollection.cpp
// Collect-card system. Drops are generated by mob loot tables; on pickup
// the card is added to the player's collection book. Completing a set
// grants a permanent stat bonus.
#include "../ShineObject.h"
namespace shine {
class CardCollection {
public:
    static CardCollection& Get() { static CardCollection s; return s; }
    bool AddCard (ShinePlayer* pkP, uint32 uiCardId) { (void)pkP; (void)uiCardId; return true; }
    bool HasSet  (ShinePlayer* pkP, uint32 uiSetId)  { (void)pkP; (void)uiSetId;  return false; }
};
class CardDeck { public: static CardDeck& Get() { static CardDeck s; return s; } };
} // namespace shine
